### ISSUE TITLE
Week 14: Code review

### ISSUE THREAD

**Issue by kuexiong** [Han434/pocketedDays#10]
@Han434 

# Design/Code Review 2

#### Reviewer: Kue Xiong (used QA Plug to review code)

| Areas for Improvement                                                                                                                                                                          |Criteria| Items Met or Exceeded       |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|-----------------------------|
|                                                                                                                                                                                                |**Project effectively utililizes the technologies and technques specified in the project objectives**|                             |
|                                                                                                                                                                                                | Planned MVP Functionality | M                           |
|                                                                                                                                                                                                | Logging framework used, i.e., no System.out.println() or printStacktrace() statements.| M                           |
| Variabes in entities, such as "userName" in "User" doens't have Hibernate annotations.                                                                                                         | Hibernate used for all data access. |                             |
|                                                                                                                                                                                                | Authentication implemented. | M                           |
|                                                                                                                                                                                                | Consumes at least one web service or public api using Java. | M                           |
| Servlets are present for full CRUD. I am just not sure how the table columns are accessed since there no Hibernate annotations in the entity classes.                                          | Application is database-driven using full CRUD.|                             |
|                                                                                                                                                                                                | Database includes multiple one to many relationships. | M                           |
|                                                                                                                                                                                                | Deployed to AWS for public access. | M                           |
|                                                                                                                                                                                                | Implements best practices (for example, data validation)  | M (data validation in JSPs) |
|                                                                                                                                                                                                | **Synthesis of multiple concepts in unfamiliar situations requiring research beyond the scope of the class**|                             |
|                                                                                                                                                                                                |Experiments individually, exhibits independence and drive, shows originality in the solution.|                             |
|                                                                                                                                                                                                |Implemented technologies or techniques not covered in course materials. |                             |
|                                                                                                                                                                                                |**Code quality - Evaluate  code quality for the following and identify specific areas for improvement (class, method or line number). Be sure to list which code quality plugins/tools you used to assist with this analysis**|                             |
|                                                                                                                                                                                                | Single-purpose methods | M                           |
|                                                                                                                                                                                                | Well-structured project|                             |
|                                                                                                                                                                                                | Descriptive naming of packages, classes, methods, variables | M                           |
|                                                                                                                                                                                                |Classes appropriately-sized  (no monster classes)| M                           |
|                                                                                                                                                                                                | CPD (copy paste detection, meaning are the same lines of code repeated?| M                           |
|                                                                                                                                                                                                | Are there candidates for super/subclass relationships, abstract classes, interfaces |                             |||are any values hard-coded that should be in a properties file? ||
|                                                                                                                                                                                                |Proper exception handling | M                           |
| Need custom error pages                                                                                                                                                                        |Proper error reporting to the user - custom erro pages?|                             | 
|                                                                                                                                                                                                |Code documentation| M                           | 
|                                                                                                                                                                                                | Is there code in the servlet doGet/doPost that should be refactored into testable classes or methods? | M                           |
| JSPs contain data validation, which is good. However, there are some HTML inline styling that could be moved to a separate stylesheet. That would allow for easier readability and management. |Evaluate the JSPs for templating, data validation, overall look and feel.|                             |
|                                                                                                                                                                                                | JSPs use JSTL and EL, no java code | M                           || |
|                                                                                                                                                                                                | Unit tests are truly a unit test rather than a high level functional test |                             | 
|                                                                                                                                                                                                |Test data is appropriately cleaned up or handled| M                           | 
|                                                                                                                                                                                                |There is full coverage of methods that perform business logic or utility functions|                             |
|                                                                                                                                                                                                |Redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After| M                           |
| Remove https config files for cognito.                                                                                                                                                         |Other comments/notes?|                             |
|                                                                                                                                                                                                |**Demonstrates initiative and thoughtful planning to leverage available resources (time, equipment, external expertise) to meet milestones and project objectives.** |                             |
|                                                                                                                                                                                                | **Evidence of significant revision and incorporation of feedback.** |                             |
| There is a lot going here. There are multiple CRUD levels.                                                                                                                                     | **Project complexity** | E                           |
|                                                                                                                                                                                                | **Additional Comments** |                             |

**Comment by Han434** [comment]
Thank you @kuexiong.

**Comment by pawaitemadisoncollege** [comment]
Hi @kuexiong - thanks for your review and providing some detailed areas for improvement.  In the future, feedback like this would be improved by sharing how or why a given item has achieved a M or E.  Also including what the results of running QAPlug were would be helpful.
