### ISSUE TITLE
Peer Review 1 - Keith Lienert

### ISSUE THREAD

**Issue by klienert** [Han434/pocketedDays#3]
## Myo Min Han Peer Review
@Han434
@pawaitemadisoncollege 

### Problem Statement

I think you are on the right track in describing the purpose. I like the David Allen quote, just mind the comma: 
- _Your mind is for having ideas, not holding them._  

*You could be more specific with how your application can be customized. Your bullet point _That is one of the reason why I decide to develop an application that can do what I exactly want to manage my rush life_ is vague. You could also simplify this by stating that you are creating a "task manager" (or come up with a different term) in the style of "Notion" but that has a particular customized option that you added. 

### Design Documentation

Nice job with this! Very inspiring!!
- User stories pinpoint the MVP
- Application flow is highly detailed
- Screen Designs are awesome!!
  - I can see what you mean with the app holding financial records for now - I think you have the 'bones' of the project to transition to a more task-oriented structure
 
### Data Model/DB
**Good stuff!!** Just looking at your ERD, I think you have most of everything covered, just a couple of thoughts:
- User
  - Make 'name' into first_name and last_name
  - Is there other info for the User that you will need?
- Do you think the tables that have a createdDate OR dateCreated column could also benefit from a updatedDate column?
- As you consider adding a 'Task Management' option, maybe a separate table ('Type'??) that could then branch off to all of the elements that are involved in your Task Management feature. 

### Code

- [x] Proper maven structure
  - This looks good! 
- [x] .gitignore file for IntelliJ
- [x] No redundant copy/paste in JSP or classes
  - To be honest, there are a lot of JSPs in this, any chance to consolidate them? 
  - Something to consider... if you add a task-manager option, this could potentially double (or more) the number of JSP files...
  - Similar thought with the classes... @pawaitemadisoncollege, any thoughts?
- [x] classes are not monster-sized
- [x] Logging statements used instead of sys.out.print
  - I did not see any System.out.println statements :)
  - Looks like you are using the logger for INFO -- [pocketedDays.log](https://github.com/Han434/pocketedDays/blob/main/EntJavaprojectspocketedDayslogs/pocketedDays.log) 
- [x] appropriate unit tests 
  - So far, so good! 

Nice work with this Myo!!

**Comment by Han434** [comment]
Thanks Keith.

**Comment by pawaitemadisoncollege** [comment]
Thanks @klienert for your careful review of @Han434's project so far!


Your observation about the number of controllers is a good one - I wonder if the edit and create might be combined? Same idea with the jsps - for example, the createProject and editProject jsps share a LOT of the same code. 

There are some sneaky printStackTraces in the PropertiesLoader. ![Screen Shot 2023-03-08 at 3 36 04 PM](https://user-images.githubusercontent.com/13874466/223855896-4ef6943c-d59d-46bb-8902-4215c3025c68.png)

**Comment by Han434** [comment]
@pawaitemadisoncollege Is there a way to log in an interface?

**Comment by pawaitemadisoncollege** [comment]
Hi @Han434 I generally think it's not a great idea to put the logger right in the interface, as generally we don't know what logging mechanism the implementor might have.  

HOWEVER, since you DO know in the case of this project that the implementation will use Log4J, you can put the logger in the interface. Here's how ChatGPT explains  it: 
<img width="919" alt="Screen Shot 2023-04-02 at 2 12 27 PM" src="https://user-images.githubusercontent.com/13874466/229374234-87a4ca5e-9743-46e8-80a1-0d03d0be600f.png">

**Comment by Han434** [comment]
Thanks
