### ISSUE TITLE
Week 9 ready for review

### ISSUE THREAD

**Issue by Han434** [Han434/pocketedDays#7]
@pawaitemadisoncollege week 9 is complete

1. I learned how to make my own web service.
2. Paths are a bit hard to remember. But that is not that much.
3. Everything went pretty well. I didn't face any problems.

**Comment by pawaitemadisoncollege** [comment]
Hi @Han434 Can you point me to the code you'd like reviewed for week 9? Thanks!

**Comment by Han434** [comment]
Oh sorry, I forgot to push the codes. Thank you for letting me know.

**Comment by pawaitemadisoncollege** [comment]
Hi @Han434! This looks like a good start at practicing building RESTful web services with java.  

- [x] Be sure to review the best practices for resource naming. https://github.com/Han434/pocketedDays/blob/cb37c45c87e64a583467e463061e8e4cc2066526/src/main/java/com/pocketedDays/rest/RowService.java#L11 should be improved!  `@Path("/rows") `
